# Generated by Django 4.1.4 on 2022-12-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_remove_photo_names_metaname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_name', to='photo.photo')),
            ],
        ),
        migrations.DeleteModel(
            name='MetaName',
        ),
    ]
