# Generated by Django 4.1.4 on 2022-12-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photoname_delete_metaname'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='names',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhotoName',
        ),
    ]
