# Generated by Django 4.1.4 on 2022-12-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_names_delete_photoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='geo_location',
            field=models.CharField(max_length=100, verbose_name='Геолокация'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='names',
            field=models.CharField(max_length=100, verbose_name='Имена'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
