# Generated by Django 4.1.4 on 2022-12-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_remove_photo_names_photoname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_people', to='photo.photo')),
            ],
        ),
        migrations.DeleteModel(
            name='PhotoName',
        ),
    ]
