# Generated by Django 4.1.4 on 2022-12-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_accesskey_site_user_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='geo_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Геолокация'),
        ),
        migrations.DeleteModel(
            name='AccessKey',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
